### ISSUE TITLE
AIATimeLags missing

### ISSUE THREAD

**Issue by weaselskinghenry** [rice-solar-physics/synthetic-observables-paper-models#9]
Hello, it looks like AIATimeLags has been removed from the repository, though references to it remain; can this be added, please? Thanks!

**Comment by wtbarnes** [comment]
Hi! This repository is actually tied to a specific (and old!) version of the synthesizAR code (https://github.com/wtbarnes/synthesizAR) which used to contain the `AIATimeLags` object but has now been removed (see this commit: https://github.com/wtbarnes/synthesizAR/commit/37f955f0298999739a10e053dcd27c9427e4b5a2. You can check out the repo prior to this commit if you wanted to use the old implementation).

For calculating time lags in Python, I would actually recommend using the sunkit-image package. This example will likely be useful: https://docs.sunpy.org/projects/sunkit-image/en/stable/generated/gallery/calculating_time_lags.html#sphx-glr-generated-gallery-calculating-time-lags-py. 

The underlying code for computing the time lags is the same (I wrote both implementations and the approach is described in the appendix of the paper for this repo). The purpose of moving it to sunkit-image was to make it a bit more flexible/general and user-friendly. If you are using Dask to compute these in parallel, this will still work in the sunkit-image implementation.

**Comment by weaselskinghenry** [comment]
Great, thanks so much!
